PI = 3.14
GRAVITY = 9.8
SCREEN_SHOT = "ScreenShot"

TESTING_METHOD = "TestingMethod"
BASE_SCREEN_SHOT = "BaseScreenShot"
TESTING_SCREENSHOT = "TestingScreenShot"
DIFF = "Diff"

TESTING_PHONE_NUMBER = "92470640"
TESTING_PASSWORD = "1ppppppppppp"